### ISSUE TITLE
froms disable pointing device example does not seem to work

### ISSUE THREAD

**Issue by atanasj** [yqrashawn/GokuRakuJoudo#121]
I am trying to use the example that was provided that disables pointing devices. 

```clojure
 {:froms {:from-any-pointing-button {:any "pointing_button"}}
         :main [{:des "disable all pointing button"
                 :rules [[:from-any-keycode-key :vk_none]
                         [{:any "pointing_button"} :vk_none]]}]}
```

However, I get the following error:

```sh
❯ goku
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn
        at karabiner_configurator.keys$parse_key.invokeStatic(keys.clj:158)
        at karabiner_configurator.keys$parse_key.doInvoke(keys.clj:146)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at karabiner_configurator.froms$parse_from.invokeStatic(froms.clj:121)
        at karabiner_configurator.froms$parse_from.invoke(froms.clj:118)
        at karabiner_configurator.froms$generate$iter__1225__1229$fn__1230.invoke(froms.clj:133)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
        at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$into.invokeStatic(core.clj:6895)
        at clojure.core$into.invoke(core.clj:6887)
        at karabiner_configurator.froms$generate.invokeStatic(froms.clj:127)
        at karabiner_configurator.froms$generate.invoke(froms.clj:125)
        at karabiner_configurator.froms$parse_froms.invokeStatic(froms.clj:137)
        at karabiner_configurator.froms$parse_froms.invoke(froms.clj:135)
        at karabiner_configurator.core$parse_edn.invokeStatic(core.clj:88)
        at karabiner_configurator.core$parse_edn.invoke(core.clj:70)
        at karabiner_configurator.core$parse.invokeStatic(core.clj:147)
        at karabiner_configurator.core$parse.doInvoke(core.clj:139)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at karabiner_configurator.core$_main.invokeStatic(core.clj:229)
        at karabiner_configurator.core$_main.doInvoke(core.clj:224)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at karabiner_configurator.core.main(Unknown Source)


```

Am I doing something wrong or does this not work?

**Comment by yqrashawn** [comment]
Hi, please use keyword `:pointing_button` instead of string.
