### ISSUE TITLE
goku runtime exception

### ISSUE THREAD

**Issue by Gandharikos** [yqrashawn/GokuRakuJoudo#167]
I'm newcomer, I paste and run a example from official tutorial, then I got this.(my devics is m1 mac)
Exception in thread "main" java.lang.RuntimeException: EOF while reading
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.EdnReader.read(EdnReader.java:130)
        at clojure.lang.EdnReader.read(EdnReader.java:111)
        at clojure.edn$read.invokeStatic(edn.clj:35)
        at clojure.edn$read.invokeStatic(edn.clj:14)
        at clojure.edn$read.invoke(edn.clj:14)
        at karabiner_configurator.misc$load_edn.invokeStatic(misc.clj:41)
        at karabiner_configurator.misc$load_edn.doInvoke(misc.clj:35)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at karabiner_configurator.core$parse.invokeStatic(core.clj:150)
        at karabiner_configurator.core$parse.doInvoke(core.clj:142)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at karabiner_configurator.core$_main.invokeStatic(core.clj:239)
        at karabiner_configurator.core$_main.doInvoke(core.clj:234)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at karabiner_configurator.core.main(Unknown Source)

**Comment by dewinterjack** [comment]
I am having this issue too on M1

**Comment by ibehnam** [comment]
I'm having the same issue on M1 Mac.

**Comment by januz** [comment]
I have a similar error message on an M1 Mac. Goku used to work until recently though.

```
Exception in thread "main" java.lang.RuntimeException: Unsupported escape character: \ 
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader$StringReader.invoke(EdnReader.java:457)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$VectorReader.invoke(EdnReader.java:672)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
	at clojure.lang.EdnReader.read(EdnReader.java:145)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.edn$read.invokeStatic(edn.clj:35)
	at clojure.edn$read.invokeStatic(edn.clj:14)
	at clojure.edn$read.invoke(edn.clj:14)
	at karabiner_configurator.misc$load_edn.invokeStatic(misc.clj:38)
	at karabiner_configurator.misc$load_edn.doInvoke(misc.clj:32)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at karabiner_configurator.core$parse.invokeStatic(core.clj:138)
	at karabiner_configurator.core$parse.doInvoke(core.clj:130)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at karabiner_configurator.core$_main.invokeStatic(core.clj:229)
	at karabiner_configurator.core$_main.doInvoke(core.clj:224)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at karabiner_configurator.core.main(Unknown Source)
```

Any idea what might be going wrong? Thanks!

**Comment by nbbaier** [comment]
I also have this issue on an M2 Mac

**Comment by yqrashawn** [comment]
Hi all, In most cases, this error means there's unbalanced parens/brakets in edn file.
