### ISSUE TITLE
Seems goku can't find joker bin file when running with brew service

### ISSUE THREAD

**Issue by yqrashawn** [yqrashawn/GokuRakuJoudo#17]
```
Exception in thread "main" java.io.IOException: Cannot run program "joker": error=2, null
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.io.IOException.<init>(IOException.java:81)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at clojure.java.shell$sh.invokeStatic(shell.clj:113)
	at clojure.java.shell$sh.doInvoke(shell.clj:79)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at karabiner_configurator.core$check_edn_syntax.invokeStatic(core.clj:86)
	at karabiner_configurator.core$check_edn_syntax.invoke(core.clj:85)
	at karabiner_configurator.core$parse_edn.invokeStatic(core.clj:89)
	at karabiner_configurator.core$parse_edn.invoke(core.clj:88)
	at karabiner_configurator.core$_main.invokeStatic(core.clj:157)
	at karabiner_configurator.core$_main.doInvoke(core.clj:152)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at karabiner_configurator.core.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
Caused by: java.io.IOException: error=2, null
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.io.IOException.<init>(IOException.java:58)
	at com.oracle.svm.core.posix.Target_java_lang_UNIXProcess.forkAndExec(PosixJavaLangSubstitutions.java:319)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBui
```

**Comment by yqrashawn** [comment]
fixed https://github.com/yqrashawn/GokuRakuJoudo/commit/24cec578fb0ee49f549601c8ab7d5bac1813ab60
