### ISSUE TITLE
I always get Key must be integer

### ISSUE THREAD

**Issue by hardikhhh1** [yqrashawn/GokuRakuJoudo#2]
Hey there, 

Just trying to use this library but still its not working for me.

I used the example in the tutorial.

When i run 
```
goku
```

I get the following 
```
Exception in thread "main" java.lang.IllegalArgumentException: Key must be integer
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.RuntimeException.<init>(RuntimeException.java:62)
	at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:52)
	at clojure.lang.APersistentVector.assoc(APersistentVector.java:345)
	at clojure.lang.APersistentVector.assoc(APersistentVector.java:18)
	at clojure.lang.RT.assoc(RT.java:792)
	at clojure.core$assoc__4371.invokeStatic(core.clj:191)
	at clojure.core$assoc__4371.invoke(core.clj:190)
	at karabiner_configurator.core$update_to_karabiner_json.invokeStatic(core.clj:76)
	at karabiner_configurator.core$update_to_karabiner_json.invoke(core.clj:66)
	at karabiner_configurator.core$parse_edn.invokeStatic(core.clj:82)
	at karabiner_configurator.core$parse_edn.invoke(core.clj:81)
	at karabiner_configurator.core$_main.invokeStatic(core.clj:150)
	at karabiner_configurator.core$_main.doInvoke(core.clj:145)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at karabiner_configurator.core.main(Unknown Source)
	at [com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)](url)
```
Can there be better example added?

**Comment by yqrashawn** [comment]
You need to create a profile named "Goku" in Karabiner-Elements GUI as below.

<img width="1679" alt="screen shot 2018-10-04 at 2 03 20 am" src="https://user-images.githubusercontent.com/15090582/46429793-e6166e00-c779-11e8-973d-55ec0264a33e.png">

**Comment by yqrashawn** [comment]
I'm pretty sure it's the profile problem. So I'll close the issue. Feel free to reopen it if it still broken.
