### ISSUE TITLE
Running goku / gokuw command gives errors

### ISSUE THREAD

**Issue by hardikhhh1** [yqrashawn/GokuRakuJoudo#5]
Hey there,

This is my first time trying to run goku. I added an example to by karabiner.edn as described in the tutorial.

Now when I run goku command i get:

```
Exception in thread "main" java.lang.IllegalArgumentException: Key must be integer
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Exception.<init>(Exception.java:66)
        at java.lang.RuntimeException.<init>(RuntimeException.java:62)
        at java.lang.IllegalArgumentException.<init>(IllegalArgumentException.java:52)
        at clojure.lang.APersistentVector.assoc(APersistentVector.java:345)
        at clojure.lang.APersistentVector.assoc(APersistentVector.java:18)
        at clojure.lang.RT.assoc(RT.java:792)
        at clojure.core$assoc__4371.invokeStatic(core.clj:191)
        at clojure.core$assoc__4371.invoke(core.clj:190)
        at karabiner_configurator.core$update_to_karabiner_json.invokeStatic(core.clj:76)
        at karabiner_configurator.core$update_to_karabiner_json.invoke(core.clj:66)
        at karabiner_configurator.core$parse_edn.invokeStatic(core.clj:82)
        at karabiner_configurator.core$parse_edn.invoke(core.clj:81)
        at karabiner_configurator.core$_main.invokeStatic(core.clj:150)
        at karabiner_configurator.core$_main.doInvoke(core.clj:145)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at karabiner_configurator.core.main(Unknown Source)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:163)
```

**Comment by hardikhhh1** [comment]
Forgot to mention, i installed it using brew.

**Comment by yqrashawn** [comment]
As I said, you need to use Karabiner-Elements GUI to create a profile named "Goku", that error mens it can't find the "Goku" profile to replace in `karabiner.json` file.

**Comment by hardikhhh1** [comment]
I had a profile name "goku", sorry about that. Thanks
